trigger:
- master

name: $(Date:yyyyMMdd).$(Rev:rrr) ($(Build.BuildNumber))

pool:
  vmImage: vs2017-win2016  
  
variables:
  BuildPlatform: Any Cpu
  BuildConfiguration: Release
  
steps:
- script: set DOTNET_CLI_TELEMETRY_OPTOUT=true
  displayName: Disable dotnet telemetry  
#- bash: export DOTNET_CLI_TELEMETRY_OPTOUT=true
#  displayName: Disable dotnet telemetry

- template: build/steps/build.yml
  parameters:
    solution: Auditing.sln
    solutionName: Auditing
    
- template: build/steps/test.yml

- task: PublishTestResults@2
  inputs:
    runner: xUnit
    mergeTestResults: true
    testResultsFiles: '**/TEST-*.trx'
    # Default path for writing test results
    searchFolder: $(Agent.TempDirectory) 
    
- task: PublishBuildArtifacts@1
  displayName: Publish assembly
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/bin
    ArtifactName: $(BuildConfiguration)
  condition: and(succeeded(), eq(variables['system.pullrequest'], false))
    
- task: PublishBuildArtifacts@1
  displayName: Publish NuGet 
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/NuGet
    ArtifactName: NuGet
  condition: and(succeeded(), eq(variables['system.pullrequest'], false))
