trigger:
- master

name: $(Rev:r) 
#'Auditing $(Date:yyyyMMdd).$(Rev:.r)'

pool:
  vmImage: vs2017-win2016
  
variables:
  BuildPlatform: Any Cpu
  BuildConfiguration: Release
  
steps:
- template: build/steps/build.yml
  parameters:
    solution: Auditing.sln
    solutionName: Auditing
    
- template: build/steps/test.yml
  parameters:
    displayName: Unit Tests
    projectsPath: tests/*.Tests.csproj
    
- task: PublishBuildArtifacts@1
  displayName: Publish assembly
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/bin
    ArtifactName: $(BuildConfiguration)
  condition: and(succeeded(), eq(variables['system.pullrequest'], false))
    
- task: PublishBuildArtifacts@1
  displayName: Publish NuGet 
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/NuGet
    ArtifactName: NuGet
  condition: and(succeeded(), eq(variables['system.pullrequest'], false))
