trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: vs2017-win2016  
  
variables:
  BuildPlatform: Any Cpu
  BuildConfiguration: Release
  SourceVersionShort: ''
  #ProjectsPaths: '**/*.csproj'
  
steps:
- powershell: |
    Write-Host "& git rev-parse --short $(Build.SourceVersion)"
  displayName: Set short source version
- script: |
    set DOTNET_CLI_TELEMETRY_OPTOUT=1
    set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true    
  displayName: Set environment variables
#- bash: export DOTNET_CLI_TELEMETRY_OPTOUT=true
#  displayName: Disable dotnet telemetry

- script: echo "Build triggered for reason '$(Build.Reason)' (commit $(Build.SourceVersion)) on branch '$(Build.SourceBranchName)'"
  displayName: Build information

- template: build/steps/build.yml
    
- template: build/steps/test.yml

- task: PublishTestResults@2
  inputs:
    runner: xUnit
    mergeTestResults: true
    testResultsFiles: '**/*.trx'
    # Default path for writing test results
    searchFolder: $(Agent.TempDirectory) 
    
- task: PublishBuildArtifacts@1
  displayName: Publish assembly
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/bin
    ArtifactName: $(BuildConfiguration)
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    
- task: PublishBuildArtifacts@1
  displayName: Publish NuGet 
  inputs:
    PathToPublish: $(Build.ArtificatStagingDirectory)/NuGet
    ArtifactName: NuGet
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
